- yay:
    - anki
    - aurphan
    - broot
    - bspwm
    - discord-canary
    - git
    - htop
    - iwd
    - make
    - man-pages
    - mpv
    - neovim
    - nitrogen
    - p7zip
    - progress
    - ranger
    - reflector
    - rsync
    - screenfetch
    - spotify
    - sudo
    - syncplay
    - tldr
    - tmux
    - tree
    - tumbler
    - units
    - xclip
    - xreader
    - xterm
    - yay
    - youtube-dl
