- yay:
    - anki
    - aurphan
    - broot
    - bspwm
    - ungoogled-chromium
    - discord-canary
    - dmenu
    - git
    - gvfs
    - htop
    - iwd
    - jetbrains-toolbox
    - make
    - man-pages
    - mpv
    - neovim
    - nitrogen
    - p7zip
    - pavucontrol
    - polybar
    - progress
    - ranger
    - reflector
    - rofi
    - rsync
    - screenfetch
    - spotify
    - sudo
    - sxhkd
    - syncplay
    - thunar
    - thunar-volman
    - thunar-vcs-plugin
    - thunar-media-tags-plugin
    - thunar-archive-plugin
    - tldr
    - tmux
    - tree
    - tumbler
    - units
    - wmname
    - xclip
    - xorg-server
    - xreader
    - xterm
    - yay
    - youtube-dl
