- shell:
    - ["chmod +x ./scripts/install_zsh.sh", "Making zsh installation script executable"]
    - ["./scripts/install_zsh.sh", "Installing zsh"]

- link:
    ~/.zshrc:       shells/zsh/zshrc
    ~/.zprofile:    shells/zsh/zprofile
    ~/.zshenv:      shells/zsh/zshenv
    ~/.zlogin:      shells/zsh/zlogin
    ~/.funcs:       shells/zsh/funcs
