#!/usr/bin/env sh

#
# ENVIRONMENT VARIABLES
#

# PATH management
typeset -U PATH path
path=(
  "/home/${USER}/.local/bin"
  "/home/${USER}/.go/bin"
  "/home/${USER}/.cargo/bin"
  "/home/${USER}/.local/share/JetBrains/Toolbox/scripts"
  "${path[@]}"
  "/opt/flutter/bin"
	)
export PATH

# Basic XDG variables
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"

# ZSH variables
#export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
#export HISTFILE="$ZDOTDIR/.zhistory"
export HISTFILE="$XDG_CONFIG_HOME/.zhistory"
export HISTSIZE=2048
export SAVEHIST=4096

# Cleaning $HOME
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority

export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

# Figure out in the future
#export GOPATH="$WORKSPACE/go"
#export GOBIN="$WORKSPACE/go/bin"
#export GOCACHE="$XDG_CACHE_HOME/go-build"

# Best editor
export EDITOR=nvim
export VISUAL=nvim

# GPG
export GPG_TTY=$(tty)

# Java HiDPI
#export JDK_JAVA_OPTIONS='-Dsun.java2d.uiScale=2'
#if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
#  export MOZ_ENABLE_WAYLAND=1
#fi
