# ZSHRC

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1024
SAVEHIST=2048
bindkey -e
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle :compinstall filename '/home/seqre/.zshrc'

autoload -Uz compinit
compinit
promptinit
# End of lines added by compinstall

alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias la='ls -a'
alias lA='ls -A'

source /home/seqre/.config/broot/launcher/bash/br
alias airpods="bluetoothctl power on && bluetoothctl connect 80:82:23:9D:5E:F4"
