#! /bin/sh

#
# Spinning up additional programs
#

{
	killall -q sxhkd;	sxhkd &
	killall -q polybar;	polybar main --config=~/.config/polybar/config.ini &
} >/dev/null 2>&1

# Fixes some Java window problems
wmname LG3D

nitrogen --set-scaled ${HOME}/.local/share/backgrounds/2289864.svg

#
#

# Multimonitor setup
#

bspc monitor -d "www" 2 3 4 5 6 "discord"

#
# General config
#

bspc config border_width         	3
bspc config window_gap           	30 

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false

#bspc config pointer_modifier			control

#
# Pywal color config
#
. "${HOME}/.cache/wal/colors.sh"

#bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

#
# Rules
#

bspc rule -a mpv 								state=fullscreen
bspc rule -a URxvt 							state=floating 		center=on
bspc rule -a XTerm 							state=floating 		center=on
bspc rule -a Xfce4-terminal			state=floating 		center=on
bspc rule -a kitty 							state=floating 		center=on rectangle=1400x900+0+0
bspc rule -a Gimp 							state=floating
bspc rule -a jetbrains-toolbox 	state=floating
bspc rule -a Thunar						 	state=floating
bspc rule -a Steam							state=pseudo_tiled
