#! /bin/sh

{
	killall -q sxhkd;				sxhkd &
	killall -q polybar;			polybar seqre &
} >/dev/null 2>&1

# Fixes some Java window problems
wmname LG3D

nitrogen --set-scaled /usr/share/backgrounds/2289864.svg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           20 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv state=fullscreen
bspc rule -a URxvt state=floating center=on
bspc rule -a XTerm state=floating center=on
bspc rule -a Gimp state=floating
bspc rule -a jetbrains-toolbox state=floating
