#! /bin/sh

wmname LG3D
sxhkd &
$HOME/.config/polybar/launch.sh

nitrogen --set-scaled /usr/share/backgrounds/2289864.svg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv state=fullscreen
bspc rule -a URxvt state=floating center=on
bspc rule -a XTerm state=floating center=on
bspc rule -a Gimp state=floating
#bspc rule -a jetbrains-pycharm follow=on
#bspc rule -a jetbrains-clion follow=off
#bspc rule -a jetbrains-idea follow=off
