# Inserts a blank line between shell prompts
add_newline = true

[[battery.display]]
threshold = 15

[directory]
fish_style_pwd_dir_length = 1

[git_commit]
tag_disabled = false

[git_metrics]
disabled = false

[hostname]
ssh_only = false

[memory_usage]
disabled = false

[status]
disabled = false

[time]
disabled = true
