#!/usr/bin/env sh

#
# Aliases
#

alias grep='grep --color=auto'
alias ip='ip -c'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -l'
alias la='ls -a'
alias lA='ls -A'
alias lla='ls -al'
alias tree='tree --dirsfirst -C'

alias vim='nvim'
alias v='nvim'

alias sudo='sudo -v; sudo '

alias scl='systemctl'
alias jcl='journalctl'
alias here='gnome-terminal --tab'

alias p1='ping 1.1.1.1'
