#!/usr/bin/env sh

#
# Aliases
#

alias grep='grep --color=auto'
alias ls='ls --color=auto --group-directories-first'
alias la='ls -a'
alias lA='ls -A'

alias emerge="time emerge --ask"

alias vim='nvim'
alias v='nvim'

alias airpods="bluetoothctl power on && bluetoothctl connect 80:82:23:9D:5E:F4"
