[alias]
b = "build"
c = "check"
d = "doc"
t = "test"
r = "run"


[build]
target-dir = "./.local/share/cargo/target"
rustflags = ["-Z", "threads=8"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
