[alias]
b = "build"
c = "check"
d = "doc"
t = "test"
r = "run"
u = "update"

[build]
target-dir = "./.local/share/cargo/target"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
